name: integration-tests
on:
  push:
    branches: [943-github-actions-cypress]

env:
  # pass GitHub token to allow accurately detecting a build vs a re-run build
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  # commenting out because image is already available
  # build-artifact:
  #   runs-on: ubuntu-latest
  #   name: build & push image with mssql base image
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - name: build-and-push-image
  #       uses: docker/build-push-action@v1
  #       with:
  #         username: nclairesays
  #         password: Dogfood!1
  #         repository: nclairesays/tdm-test
  #         dockerfile: ./Dockerfile
  #         tag_with_ref: true
  #         tag_with_sha: true
  #         add_git_labels: true
  #         labels: description="TDM Calculator",maintained="tdm+cicd@hackforla.org"

  # doesn't work:
  # build-artifact-v2:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: nclairesays/tdm-test:latest
  #   steps:
  #     - name: Directory cleanup
  #       run: rm -rf ..?* .[!.]* *
  #     - name: Checkout Code
  #       uses: actions/checkout@v2
  #     - name: Build Artifact
  #       run: |
  #         pwd
  #         ls -al
  #         cd client
  #         ls -al
  #         npm run build
  #         ls -al
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: tdmapp
  #         path: /build/
  #     - name: Dump Env
  #       run: |
  #         env | sort
  #         ls -la
  #     - name: Cleanup
  #       if: ${{ always() }}
  #       run: |
  #         rm -rf ..?* .[!.]* *

  install-and-build:
    runs-on: ubuntu-latest
    # needs: build-artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print versions
        run: |
          which npm
          npm --version
          which yarn
          yarn --version

      - name: Install NPM
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Print versions
        run: |
          which npm
          npm --version
          which yarn
          yarn --version
      # only install the dependencies without running any tests from root folder
      - name: Cypress Install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      - name: Install Modules and Build
        run: |
          cd ./server
          npm install
          cd ../client
          npm install
          npm run build
      - name: echo
        run: |
          pwd
          echo "****** inside root directory: ******"
          ls -al .
          pwd
          echo "****** inside client directory ******"
          ls -al ./client
      - name: Save to build folder in root directory
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: |
            ./client/build
      - name: Save to cypress folder in root directory
        uses: actions/upload-artifact@v2
        with:
          name: cypress
          if-no-files-found: error
          path: |
            ./cypress

  cypress-test:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download build folders ⏬
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: List current directory
        run: pwd
          ls -al
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install: false
          working-directory: cypress
          start: npm start-all-servers
      # # install dependencies and run the tests
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run expect -- --env lastName=Smith
      #   env:
      #     CYPRESS_firstName: Joe
      # - name: Cypress run
      #   uses: cypress-io/github-action@v2
      #   with:
      #     start: npm start
      #     wait-on: "http://localhost:3000"
      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -rf ..?* .[!.]* *

  # cypress-run:
  #   runs-on: ubuntu-latest
  #   needs: install-and-build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: checkout directory
  #       run: pwd
  #         ls -al
  #     - name: Start Database
  #       run: ./.github/start-db.sh
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: npm start
  #         wait-on: "http://localhost:3000"
  #     - name: Cleanup
  #       if: ${{ always() }}
  #       run: |
  #         rm -rf ..?* .[!.]* *

  # cypress-run-v2:
  #   runs-on: ubuntu-latest
  #   needs: install-and-build
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: checkout directory
  #       run: pwd
  #         ls -al
  #     - name: Start Database
  #       run: ./.github/start-db.sh
  #     - name: Start app
  #       run: node server.js
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         start: npm start
  #         wait-on: "http://localhost:3000"
  #     - name: Cleanup
  #       if: ${{ always() }}
  #       run: |
  #         rm -rf ..?* .[!.]* *

  cypress-run-v3:
    runs-on: ubuntu-latest
    needs: install-and-build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: checkout directory
        run: pwd
          ls -al
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: tdmapp
          # path: /__w/tdmapp/tdmapp/build/
          path: /home/runner/work/tdm-calculator/tdm-calculator
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:3000"
      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -rf ..?* .[!.]* *

  cypress-run-v4:
    runs-on: ubuntu-latest
    container:
      image: tdmcalc/tdmapp:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: checkout directory
        run: pwd
          ls -al
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: tdmapp
          path: /__w/tdmapp/tdmapp/build/
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:3000"
      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -rf ..?* .[!.]* *

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           #build: npm run build
#           #start: npm start
#           spec: cypress/integration/project-calculations-no-auths/barrington-condos.spec.js
#           wait-on: https://tdmdev.azurewebsites.net/
#           record: true

#         env:
#           # pass the Dashboard record key as an environment variable
#           CYPRESS_RECORD_KEY: 331838a7-bd77-4de8-9a2f-6ca0ecb30414
#           # pass GitHub token to allow accurately detecting a build vs a re-run build
#           #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
