name: integration-tests
on:
  push:
    branches: [943-github-actions-cypress]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: checkout directory
        run: pwd
          ls -al
      - name: Install NPM
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - name: Install Server Node Modules
        run: cd ./server && npm install
      - name: Install Client Node Modules
        run: cd ../client  && npm install && cd ../cypress
      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:3000"
# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
#       - name: Cypress run
#         uses: cypress-io/github-action@v2
#         with:
#           #build: npm run build
#           #start: npm start
#           spec: cypress/integration/project-calculations-no-auths/barrington-condos.spec.js
#           wait-on: https://tdmdev.azurewebsites.net/
#           record: true

#         env:
#           # pass the Dashboard record key as an environment variable
#           CYPRESS_RECORD_KEY: 331838a7-bd77-4de8-9a2f-6ca0ecb30414
#           # pass GitHub token to allow accurately detecting a build vs a re-run build
#           #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
